# Site settings
title: Incertae Sedis
email: contacto@incsed.com
description: "Incertae Sedis - Professional services and courses" # Fixed the dash here
url: "incsed.github.io"
baseurl: "" # Use empty quotes if this is your main domain; use "/website" ONLY if your URL is incertaesedis.com/website/
repository: "incsed/website"
teaser: /assets/images/500x300.png
logo: /assets/images/incico2.svg

# Minimal Mistakes theme
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: default

# Locale
locale: es-MX
language: es

# Site author
author:
  name: "Incertae Sedis"
  avatar: /assets/images/incico2.svg
  bio: "Professional services"
  location: "Mexico"
  links:
    - label: "Twitter"
      url: "https://twitter.com/"
    - label: "Facebook"
      url: "https://www.facebook.com/"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

paginate: 5
paginate_path: /page:num/

# Build settings
include:
  - _pages
exclude:
  - README.md
  - .git
  - .gitignore
  - vendor # Important to exclude the vendor folder if using Cloudflare

# Markdown
markdown: kramdown
highlighter: rouge
